package com.xkeshi.common.em;

/**
 * <br>
 * User: David <br>
 * Date: 13-11-26 <br>
 */
public enum Table {
    ASSET
    ,ASSET_CONTRACT
    ,ASSET_CONTRACT_PAWN
    ,ASSET_CONTRACT_PROCESS
    ,ASSET_PASSIVE_REDEMPTION
    ,ASSET_PROCESS
    ,ASSET_SALE_RESTRICT
    ,CLIENT
    ,CLIENT_ACCOUNT_INFO
    ,CLIENT_ASSET_INVENTORY
    ,CLIENT_CHECK
    ,CLIENT_INTENT
    ,CLIENT_REQUEST
    ,CLIENT_TRACE
    ,DEAL_ASSET
    ,DEAL_ASSET_INTEREST_INVENTORY
    ,DEAL_ASSET_INVENTORY
    ,DEAL_ASSET_REDEMPTION_INTEREST
    ,DEAL_ASSET_REDEMPTION_VOUCHER
    ,DEAL_ASSET_TRACE
    ,DEAL_ONLINE_SIGNED
    ,DEAL_P2P
    ,DEAL_PARTNERSHIP
    ,EMPLOYEE
    ,ORGANIZATION
    ,REDEMPTION_CONFIRMATION_SMS
    ,ROLE
    ,ROLE_MASTER
    ,ROLE_PERMISSION
    ,STATISTICS_DEAL_ASSET_PROFIT
    ,XREF_EMPLOYEE_ROLE;

    @Override
    public String toString(){
        return this.name().toLowerCase();
    }
}
